---
version: "2.1"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - SERVERURL=auto      # External ip
      - SERVERPORT=51820    # PORT
      - PEERS=5             # Number of clients 
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=0.0.0.0/0
      - LOG_CONFS=true
    volumes:
      - /home/pi/docker/wireguard/config:/config
    ports:
      - 51820:51820/udp
    restart: unless-stopped
